### ISSUE TITLE
Bitcoin has been removed

### ISSUE THREAD

**Issue by lukechilds** [tdickman/crypto51#39]
Bitcoin has been removed, is that intentional or just due to one of the other APIs?

**Comment by tdickman** [comment]
Definitely not intentional. It looks like it's back now, so I'm wondering if it was an issue with one of our apis.

**Comment by lukechilds** [comment]
Ah yes, all good now.

Are you rebuilding the site at a certain interval automatically? How often is it updated?

**Comment by tdickman** [comment]
Yup - it's setup to [run hourly](https://github.com/tdickman/crypto51/blob/master/.skaffold/cronjob.yaml#L6).
