### ISSUE TITLE
`attack_hourly_cost` value no longer returned.

### ISSUE THREAD

**Issue by lukechilds** [tdickman/crypto51#47]
There is no longer a number value returned for `attack_hourly_cost`, each coin has a `'?'` string instead.

This is breaking howmanyconfs.com (https://github.com/lukechilds/howmanyconfs.com/issues/12) which relies on that value in it's own calculations.

Is it possible to add support for this metric back in?

Thanks!

**Comment by tdickman** [comment]
@lukechilds Sorry about that - I'll take a look at it tonight and let you know when it's fixed.

**Comment by lukechilds** [comment]
Thanks a lot ❤️

No rush, whenever you can find some time.

**Comment by tdickman** [comment]
It looks like we'll need to move to Nicehash's v2 api as documented here: https://docs.nicehash.com/, so this is going to take a bit more time.

Happy to accept prs as always :).

**Comment by lukechilds** [comment]
Ok, I'm in the process of obtaining a new visa and moving countries so limited time at the moment but happy to look into this once I've got everything sorted.

**Comment by lukechilds** [comment]
@tdickman yup, had a little play today, it looks like it's this line always returning `0` which then breaks all the further calculations:

https://github.com/tdickman/crypto51/blob/e92a0e8d0171481f62f101b8e5600ea2b13f44cd/crypto51/app.py#L35

Will dig into `nh` code tomorrow and see what needs to be done to get it working with the new NiceHash API.

**Comment by lukechilds** [comment]
@tdickman sorry for the late response, I've been quite ill.

I spent some time looking into this but don't even seem to be able to get the project to run anymore, after setting up virtualenv with deps I just get:

```
Traceback (most recent call last):
  File "crypto51/app.py", line 12, in <module>
    nh = NiceHash()
  File "/Users/lukechilds/dev/oss/crypto51-standard/crypto51/apis/nicehash.py", line 19, in __init__
    self._buy_info = requests.get('https://api.nicehash.com/api?method=buy.info').json()
  File "/Users/lukechilds/.local/share/virtualenvs/crypto51-standard-vAU0x_mH/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Looks like some JSON error but I'm sure it was running when I first created this issue. I could even spoof NH API with `cost = n` from [here](https://github.com/tdickman/crypto51/issues/47#issuecomment-536543600). Not sure what changed. Possibly they just changed the NH API JSON response in the last few days but not sure how likely that is.

Anyway, I'm not super familiar with Python development or this codebase so thinking it would probs be quicker for me to just re-write this as a little Node.js API.

What are your thoughts?

If that's good with you then I'll be sure to expose all the info you need for your site so you can piggy back on my API like I have been on yours. Or if you'd rather keep the heavy lifting on your end then I'm totally good with that but do you think this something you could look at working on yourself?

If you take this on I'm happy to send you a BTC tip for your efforts.

Cheers, Luke ✌️

**Comment by szmarczak** [comment]
@lukechilds The API has changed. V1 no longer works. 

doesn't work: https://api.nicehash.com/api?method=buy.info (524 cloudflare timeout)
works: https://api2.nicehash.com/main/api/v2/public/buy/info

**Comment by ClemensLey** [comment]
I just want to mention that https://www.crypto51.app is an awesome project and it would be very cool if you could get it up an running again.

**Comment by lukechilds** [comment]
@ClemensLey if you have any experience with the NiceHash API we'd welcome some help with #48.
