### ISSUE TITLE
Ethereum Calculations Broken

### ISSUE THREAD

**Issue by lukechilds** [tdickman/crypto51#59]
Someone just reported this issue on howmanyconfs.com: https://github.com/lukechilds/howmanyconfs.com/issues/20#issuecomment-684747113

I just checked and it's affecting crypto51.app too.

Unfortunately I'm unable to look into this right now due to high priority work on another project but just letting you know.

If you have time to look into the issue please let me know!

And if anyone submits a PR with the fix to howmanyconfs.com there's a $50 bounty waiting for you.

**Comment by tdickman** [comment]
Detailed explanation over [here](https://github.com/lukechilds/howmanyconfs.com/issues/20#issuecomment-684865056).
